### ISSUE TITLE
How to append bitmaps efficiently ?

### ISSUE THREAD

**Issue by amaurel** [lemire/javaewah#20] opened 2012-12-12 11:51 UTC
Hello,

I need to append bitmaps efficiently.

Here's what I would like to do.

EWAHCompressedBitmap columnBitmap = new EWAHCompressedBitmap();
colBitmap.set(1);
colBitmap.set(3);
int nCol = 10
EWAHCompressedBitmap matrixBitmap = new EWAHCompressedBitmap();
for (int i = 0 ; i < nCol;i++) {
	bitmap = bitmap.append(colBitmap);
}

I am not sure where to start, could you please give some advises .

**Comment by rhasselbaum** [comment] 2015-10-28 12:49
@lemire I have a similar need to shift the bitmap (i.e. add zero bits to or remove bits from the front). In my case, I'll always be shifting by a multiple of the word size (64 bits). You alluded to an efficient way to do this. What approach do you recommend? Example code would be great. Thank you!

**Comment by lemire** [comment] 2015-10-28 14:15
@rhasselbaum 

One could do it efficiently right now with some surgery on the compressed data. But I do not think that users of the library can do it efficiently given our API.

We could extend the API to support the function you allude to, but, it would be very useful to know what the motivation is.

**Comment by rhasselbaum** [comment] 2015-10-28 15:59
My goal is to merge multiple bitmaps together through bitwise operations, but index 0 in each bitmap translates to a different point in a larger continuum. For example, suppose I have two bitmaps that represent time slots over different spans of time. When working with an individual bitmap, I want to be able to address bits relative to the start of its time span (e.g. index 0 is time *T*, index 1 is time *T+1*, etc.). But when combining bitmaps together, I need to translate their bit offsets to absolute time.

So the problem is a general one of translating relative indexes to absolute indexes in a larger value space before performing bitwise operations.

I might be able to use absolute time for all of my indexes, but I suspect it would be less efficient from a storage standpoint. Also, it prevents me from applying the same bitmap to different points in absolute time.

**Comment by lemire** [comment] 2015-10-28 18:43
@rhasselbaum  @amaurel 

This is supported as of javaewah version 1.1.0 through the "shift" function.

http://lemire.me/docs/javaewah/com/googlecode/javaewah/EWAHCompressedBitmap.html#shift-int-

Note that negative shifts are not allowed at this time, you can only "increment" the set bits by a fixed amount. However, the shift can be any integer, not just a multiple of 64. 

The function will run faster if the shift is divisible by 64 (EWAHCompressedBitmap) or divisible by 32 (EWAHCompressedBitmap32). 

Though this is implemented I want to clear up some misconceptions...

1. You should have no reason to believe that using larger values for the set bits should be less efficient regarding storage. The whole point of a format like EWAH is that long runs of zeroes are compressed down to almost nothing. 

2. This shift is not going to be free in general. It is an O(n) operation. If you constantly rely on shifting, do not be surprised if your processing speed is half of what it could be. An entire bitmap must be processed and recreated.

**Comment by lemire** [comment] 2015-10-28 18:44
Since I think I implemented what was requested, I am closing this issue.

**Closed by lemire** 2015-10-28 18:44 UTC

**Comment by rhasselbaum** [comment] 2015-10-28 19:16
Thank you very much! I was not expecting such a quick resolution. And thanks for correcting my misconception about large indexes.
